name: "Release"

on:
  release:
    types:
      - "published"

permissions: {}

jobs:
  release:
    name: "Release"
    permissions:
      contents: write
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4.2.1"

      - name: "Adjust version number"
        shell: "bash"
        run: |
          yq -i -o json '.version="${{ github.event.release.tag_name }}"' \
          "${{ github.workspace }}/custom_components/hass-fpl-component/manifest.json"

      - name: "ZIP the integration directory"
        shell: "bash"
        run: |
          cd "${{ github.workspace }}/custom_components/hass-fpl-component"
          zip custom_components/hass-fpl-component.zip -r ./

      - name: "Upload the ZIP file to the release"
        uses: softprops/action-gh-release@v2.0.4
        with:
          files: ${{ github.workspace }}/custom_components/hass-fpl-component/custom_components/hass-fpl-component.zip
